### ISSUE TITLE
If an error occurs the callback is not always given the error

### ISSUE THREAD

**Issue by lukeapage** [maxogden/extract-zip#15]
E.g. 
failing to make a symlink under windows fails without admin.
https://github.com/maxogden/extract-zip/blob/master/index.js#L139

This gets swallowed and no error is given.

**Comment by maxogden** [comment]
@lukeapage I'm not seeing the swallowed error in that link:

<img width="401" alt="screen shot 2015-12-08 at 9 29 31 am" src="https://cloud.githubusercontent.com/assets/39759/11662941/3daea0b0-9d8e-11e5-8b75-4629802c40e3.png">

**Comment by lukeapage** [comment]
it calls done(err) whereas other errors call cb(err). then nothing catches
it later.

**Comment by maxogden** [comment]
@lukeapage Ahhhh you're right, it turns out i'm not using the `async` module error handling correctly. Fixing now

**Comment by maxogden** [comment]
@lukeapage according to https://github.com/caolan/async/issues/496#issuecomment-47867003 if `done(err)` gets called in extract-zip it should cause the error to get logged here: https://github.com/maxogden/extract-zip/blob/master/index.js#L43

I think it should stop the extraction and print the error out to STDERR, that way you don't have to use DEBUG to see it

**Comment by maxogden** [comment]
@lukeapage ok electron-zip 1.3.0 is released, I improved the error handling
