### ISSUE TITLE
Uninitialized Buffer Security Vulnerability

### ISSUE THREAD

**Issue by dylanb** [maxogden/extract-zip#36]
There is an uninitialized Buffer security vulnerability in this project, introduced through `concat-stream`

https://snyk.io/vuln/npm:concat-stream:20160901

**Comment by mathieupythian** [comment]
The fix is to just bump up 'concat-stream' to version  1.5.2.  Btw, there is also an information disclosure vulnerability in 1.5.0:  https://www.sourceclear.com/registry/security/information-disclosure/javascript/sid-3652

**Comment by westy92** [comment]
Fixed in https://github.com/maxogden/extract-zip/pull/35
