### ISSUE TITLE
Need description fix about "pure" and "100%" javascript

### ISSUE THREAD

**Issue by puzrin** [maxogden/extract-zip#41]
In readme and package.json terms "pure javascript" and "100% javascript" are used. That's confusing. 

This package uses [yauzl](https://github.com/thejoshwolfe/yauzl), and it uses [binary binding to zlib](https://nodejs.org/api/zlib.html). I think, terms above should be avoided, because those mean completely different thing.

**Comment by malept** [comment]
To be pedantic, extract-zip itself has no native code in the repository. Distinguishing it from modules that are just a wrapper to a native library is the goal, I assume.

**Comment by maxogden** [comment]
the reasoning is that zlib is provided by the runtime so it doesn't count as a third party native extension

**Comment by puzrin** [comment]
If goal is to create OS-agnostic unzip for node.js, why not say this directly and clear? That's a useful thing and honorable goal :).

When i read "100% javascript" i expect this code can be executed in browser too without additional  runtimes. For compare: [jszip](https://github.com/Stuk/jszip) is really written in 100% javascript (but i don't say it's better for node.js)

**Comment by puzrin** [comment]
> the reasoning is that zlib is provided by the runtime so it doesn't count as a third party native extension

@maxogden, situation is the same as with "glutter-free" :). "Javascript" !== "node.js only". I understand you mean the good things, but terms are very confusing for people who write code for both node & browser.

**Comment by maxogden** [comment]
@puzrin with browserify you can use `require('zlib')` code in the browser

**Comment by puzrin** [comment]
@maxogden i know about such polyfill, but IMHO that's not correct argument here.

Anyway, I see no reason to fight about words. If you don't care about provided info - close this issue.
