### ISSUE TITLE
Relative path not possible anymore ?

### ISSUE THREAD

**Issue by DjulLau** [maxogden/extract-zip#43]
Hi,

Thanks for the lib.
I'm using it in an nwjs app to extract to a relative path. 
It was working great but now it throws "Target directory is expected to be absolute".

If I just remove
```
  if (path.isAbsolute(opts.dir) === false) {
    return cb(new Error('Target directory is expected to be absolute'))
  }
```
it still works so why forbidding relative path ?

Cheers,

Julien

**Comment by khawkins98** [comment]
The commit (https://github.com/maxogden/extract-zip/commit/b96c63d5e074881c5fa93214a7b8cce4f5e719e1#diff-168726dbe96b3ce427e7fedce31bb0bcR11) has also broken our use case. 

As a workaround, we've fixed to 1.6.0 for the old behaviour.

**Comment by malept** [comment]
FYI the actual commit message and reasoning is in this commit: https://github.com/maxogden/extract-zip/commit/01222c10101b32a657062de53e3acc2621232cd6

**Comment by markmeyerphoto** [comment]
I was also surprised by this. The ability to unpack an archive into a directory relative to the running code is essential. I can't always guarantee `process.cwd()` will be what we want. So I use something like:

    var unzipped = (__dirname + '/../unzipped/files/');

But the check for absolute directories throws an error. Why?

**Comment by tofutim** [comment]
I just noticed this issue as well.

**Comment by ipsjolly** [comment]
Try this one I forked for relative path support : https://www.npmjs.com/package/extract-zip-relative-path

`module.exports = async function (zipPath, opts) {
  debug('creating target directory', opts.dir)

  // if (!path.isAbsolute(opts.dir)) {
  //   throw new Error('Target directory is expected to be absolute')
  // }

  await fs.mkdir(opts.dir, { recursive: true })
  opts.dir = await fs.realpath(opts.dir)
  return new Extractor(zipPath, opts).extract()
}`
