### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by geneh** [maxogden/extract-zip#65]
In case of a bad archive, for example `https://search.maven.org/remotecontent?filepath=org/xhtmlrenderer/flying-saucer-pdf-itext5/9.1.12/flying-saucer-pdf-itext5-9.1.12-sources.jar`, yauzl library emits an error event which isn't handled. It causes a running process to crash instead of returning an error callback.
Something like the following should be added in index.js:
```
zipfile.on('error', function (err) {
   return cb(err)
})
```

**Comment by geneh** [comment]
It looks like it should already be handled by https://github.com/maxogden/extract-zip/pull/63

**Comment by AileenCGN** [comment]
We are facing the same issue at Ghost! Is it possible to get #63 merged anytime soon?

Thank you!

**Comment by malept** [comment]
Fixed in #67.
