### ISSUE TITLE
Why not relative path?

### ISSUE THREAD

**Issue by simodelle** [maxogden/extract-zip#79]
I tried to comment these lines of code:
`  /*if (path.isAbsolute(opts.dir) === false) {
    return cb(new Error('Target directory is expected to be absolute'))
  }*/
`
and if i put a relative path for target directory it works good (i need this).
Why is it possible to put only absolute path for target directory?

**Comment by malept** [comment]
This was answered in https://github.com/maxogden/extract-zip/issues/43#issuecomment-302412488

**Comment by m-cat** [comment]
For a project that is supposed to be dead-simple this is a pointless obstacle to usage. Somehow, node devs keep fudging something as simple as extracting a zip file into a given directory. Yay open source...?
