### ISSUE TITLE
 Error: EEXIST: file already exists, mkdir 

### ISSUE THREAD

**Issue by akondupalli** [maxogden/extract-zip#83]
error! { Error: EEXIST: file already exists, mkdir 'C:\abc\hhdhd\ddd\fff\www\klks\qsqsqs\a.b.i\D.P\.data'
  errno: -4075,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: 'C:\abc\hhdhd\ddd\fff\www\klks\qsqsqs\a.b.i\D.P\.data' }

**Comment by Surekha95** [comment]
May I know how you solve it?
