### ISSUE TITLE
how to determined entry has been extracted ?

### ISSUE THREAD

**Issue by Randyshu2018** [maxogden/extract-zip#84]
I want to determine if an entry has been extracted or whole operation has been finished ? is there  an callback or some events

**Comment by AlexandrHurski** [comment]
As I know, you will get into cb.

extractZip(source, {dir:target},  (err) =>{
console.log('finish here')

})

**Comment by malept** [comment]
If an entry has been extracted: use the onEntry option

If the whole operation has finished: as stated previously, use the callback.
