### ISSUE TITLE
Relaxed versions

### ISSUE THREAD

**Issue by daveisfera** [maxogden/extract-zip#87]
Can relaxed versions be used so that users of this module don't end up with multiple versions being installed or [stuck with a security vulnerability](#86)?

Or in other words, can `^` be used instead of specific versions in `package.json`

**Comment by cyclingzealot** [comment]
Others are talking about this in #85 , although true @SakiiCode's edits point to a specific version.

**Comment by SakiiCode** [comment]
Yeah, I didn't know the reason behind using a specific version so didn't want to break that practice. But the suggestion has been already commited so it should be fine now.

**Comment by daveisfera** [comment]
This is less about fixing the current issue with `minimist` and more about avoiding similar things in the future and minimizing the number of duplicate versions of a package that a user has to install
