### ISSUE TITLE
Not working with Node 14

### ISSUE THREAD

**Issue by giggio** [maxogden/extract-zip#94]
It seems that this library is not working with Node.js 14, that just came out. It seems that Node.js crashes exactly at this line (`stream.pipline`):

https://github.com/maxogden/extract-zip/blob/eb3c1edb8481bbf68da05cd3a824b1dcc697f908/index.js#L135

I am not sure if they changed something, and this is a breaking change and something needs to be updated on `extract-zip`, or if this is a bug on Node.js 14, that just came out. Anyway, it is breaking, and the issue is here.

**Comment by nstepien** [comment]
Can confirm, it's silently breaking puppeteer install script on node 14+win10 at least.

**Comment by AviVahl** [comment]
Will probably be fixed by https://github.com/nodejs/node/pull/32968

A change in Node's stream behavior caused several stream based libs to break, including node-tar

**Comment by aduh95** [comment]
I pulled the Node's PR and built it locally, unfortunately the tests are still failing...

**Comment by ronag** [comment]
I'm not quite familiar with this library. Could someone write a full repro example and I will take a look asap.

**Comment by ronag** [comment]
All extract-zip tests succeed. Do you think you could make a failing test which we can use to resolve this?

**Comment by ronag** [comment]
This works on Node master:

```js
const extract = require('./index')

async function main() {
    try {
        await extract('./Archive.zip', { dir: '/Users/ronagy/GitHub/public/extract-zip/sasd' })
        console.log('Extraction complete')
    } catch (err) {
        console.error(err)
        // handle any errors
    }
}
main()
```

**Comment by ronag** [comment]
I believe this might have been fixed through https://github.com/nodejs/node/pull/32967

**Comment by aduh95** [comment]
> All extract-zip tests succeed.

@ronag that's not what I see. Using Node.js 15 nightly, running `yarn ava`:

```
yarn run v1.22.4
(node:53652) [DEP0139] DeprecationWarning: Calling process.umask() with no arguments is prone to race conditions and is a potential security vulnerability.
(Use `node --trace-deprecation ...` to show where the warning was created)
$ ava

⠹ (node:53654) Warning: Accessing non-existent property 'levels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
⠴ extract broken zip

  6 tests failed

  verify github zip extraction worked


  Error: Promise returned by test never resolved



  opts.onEntry


  Error: Promise returned by test never resolved



  defaultDirMode


  Error: Promise returned by test never resolved



  defaultFileMode not set


  Error: Promise returned by test never resolved



  defaultFileMode


  Error: Promise returned by test never resolved



  files in subdirs where the subdir does not have its own entry is extracted


  Error: Promise returned by test never resolved

error Command failed with exit code 1.
```

Note that if your global `node` is using v13 or v12, that could explain why you all your tests as green. The exact command I type is `../node/out/Release/node node_modules/.bin/ava`.

Anyway, I believe Michaël came up with a probably simpler repro on the other thread.

**Comment by ronag** [comment]
So the problem here is that `zipFile.openReadStream` for some reason never emits `'close'` even though `autoDestroy` is enabled on the stream.

**Comment by aduh95** [comment]
The fix has been merged on Node.js repo, I can confirm extract-zip's tests are now passing. I believe we can close this issue as soon as Node.js 14.1.0 is released.

**Comment by giggio** [comment]
Just tested it on Node.js 14.1.0 and it is fixed.
