### ISSUE TITLE
Stop using process.umask()

### ISSUE THREAD

**Issue by aduh95** [maxogden/extract-zip#95]
Refs: https://github.com/nodejs/node/issues/32321

Summary: process.umask() (no args) is deprecated and will be removed.

I couldn't quite divine what this lib uses `process.umask()` for but in most cases you don't need to deal with the umask directly - the operating system will apply it automatically.

Example:

```js
const mode = 0o777 & ~process.umask();
fs.mkdirSync(dir, mode);
```

Computing the file mode that way is superfluous, it can be replaced with just this:

```js
fs.mkdirSync(dir, 0o777);
```

**Comment by malept** [comment]
🤷‍♂️ This is the commit that introduced it: https://github.com/maxogden/extract-zip/commit/6ad307a5cdf8a472b84f10d0fcee299e5c6e4f6e
