### ISSUE TITLE
(node:5859) ExperimentalWarning: The fs.promises API is experimental

### ISSUE THREAD

**Issue by dylang** [maxogden/extract-zip#97]
It doesn't feel like a good practice to use experimental features in a public module. 

```
(node:5859) ExperimentalWarning: The fs.promises API is experimental
```

When developers are getting that warning it's not easily known how to track it warnings down. It's also not a good practice to encourage developers to use `--no-warnings` to just avoid this warning because who knows what other warnings it could be hiding in the future.

This is caused by

```js
// eslint-disable-next-line node/no-unsupported-features/node-builtins
const { createWriteStream, promises: fs } = require('fs')
```

We're importing `const { promisify } = require('util')` a few lines down, could we use that `promisify` on the vanilla `fs` callback methods, or switch to well-used async wrap modules like [make-dir](https://github.com/sindresorhus/make-dir)?

I'm an indirect user of this library: I'm getting this warning because a module I use imports a module that imports a module that imports this. 😅 But I'm happy to make a PR.

**Comment by dylang** [comment]
Seems like it's no longer experimental past v10.17 according to nodejs/node#29875, closing this!

**Comment by AllanOricil** [comment]
I still have the warning when running using this library. And my node is v12.13.1

**Comment by benjaminben** [comment]
This breaks on some systems! We're doing an installation using BrightSign players, these things are unfortunately locked to node version 10.0... is there a recommended version of this lib for node version <= 10.0?
